export const projectData = [
    {
        project: 'Media Solution',
        thumbnail: '/images/project/mediasolution.png',
        date: '2023.09 ~ 2024.03.29',
        description: '데이터 폼, 레이아웃을 동적으로 생성하고 관리하여 코딩 없이 웹사이트를 생성하는 SaaS 형태의 CMS 프로젝트입니다.',
        skills: [
            'typescript',
            'nextjs',
            'react',
            'redux',
            'emotion',
        ],
        detail: [
            '미디어 솔루션 프로젝트의 전체적인 기획 및 WBS 관리, FE 개발 담당',
            'Sentry 모듈 개발로 에러 추적 모니터링 시스템 구축',
            '코드 컨벤션, Github Branch 전략 프로세스 구축 및 도입',
            'Next.js 초기 환경 셋팅 및 전체적인 기능 개발 담당',
            '생성형 데이터와 레이아웃을 연결하는 데이터 링크 모듈 구현',
            '키움페이 결제 시스템 연동 및 결제 스크립트 모듈화',
            'API 호출의 부하를 줄이고 연속된 이벤트 호출을 방지하기 위해 쓰로틀링과 디바운스 기능을 개발',
            'MUI 사용하여 어드민 페이지를 구축함으로써 개발 일정 및 예산 절감',
            '사용자 경험(UX)을 향상 시키기 위해 라이트/다크모드 개발',
        ],
    },
    {
        project: 'IHQ 바바요',
        thumbnail: '/images/project/babayo.jpg',
        date: '2022.01 ~ 2023.08',
        description: 'iHQ에서 서비스하는 숏폼 OTT 플랫폼의 프론트엔드 개발을 담당하였습니다. 앱 개발자와 협력하여 JavaScript Bridge를 활용해 네이티브와 통신하는 웹앱을 제작하였습니다.',
        skills: [
            'javascript',
            'nextjs',
            'react',
            'redux',
            'styled-components',
            'emotion',
            'mqtt',
        ],
        detail: [
            '프론트엔드 초기 셋팅 및 전반적인 화면 개발 담당',
            'Wecandeo 플랫폼과 m3u8 비디오 포맷을 이용한 라이브 스트리밍 플레이어 구현',
            'mqtt와 Sendbird api를 이용한 로그인 중복 체크 및 라이브 채팅 기능 구현',
            '자바스크립트 브릿지를 이용한 WebView에서의 APP Api 연동 개발',
            'User-Agent를 이용한 디바이스 별 기능 최적화',
            'Vidmix API를 통해 스트리밍 및 비디오 광고 시스템을 연동하여 비즈니스 모델 구축',
            'Axios 인터셉터와 JWT 토큰을 사용하여 API 인증 가드 기능을 구현함으로써 페이지 접근 보호 모듈 개발',
            'Redux 초기 셋팅 및 스토어 디자인',
            'API 응답을 경량화하고 인피니티 스크롤 및 Skeleton-UI를 적용하여 페이지 로딩 및 렌더링 속도를 평균 5초 -> 1초대로 80% 개선',
            'SSR 방식을 적용하고 Meta tag, Google Search Console, Naver Search Advisor를 통해 검색 엔진 크롤링과 노출을 극대화하여 SEO를 최적화',
            'Google, Apple, Naver, Kakao 소셜 로그인 연동',
        ],
    },
    {
        project: '블랙 클로버 모바일',
        thumbnail: '/images/project/blackclover.png',
        date: '2023.03 ~ 2023.05',
        description: '블랙 클로버 모바일 게임의 프로모션 사이트 프론트 개발을 담당하였습니다.',
        skills: [
            'typescript',
            'nextjs',
            'react',
            'redux',
            'styled-components',
        ],
        detail: [
            '페이지의 전반적인 화면 개발 및 유지보수',
            'Google Analytics, Meta Business, TikTok Business 등 사이트 추적 통계 시스템 연동 및 관리',
            '메타 태그 최적화, 소셜 미디어 콘솔 연동, 그리고 Lighthouse를 이용한 웹 표준 점수 최적화를 통해 검색 엔진 최적화',
            '웹사이트 및 빌드 최적화를 위해 정적 파일을 Azure Cloud Storage로 마이그레이션',
            'react-i18next를 이용한 일본어, 영어 사이트 번역 기능 개발',
            '크로스 브라우징 처리를 통해 웹 브라우저에서 일관된 사용자 경험을 제공',
        ],
    },
    {
        project: '맥스 무비',
        thumbnail: '/images/project/maxmovie.jpg',
        date: '2023.02 ~ 2023.03',
        description: '영화 관련 콘텐츠와 기사를 제공하는 맥스무비 웹사이트의 유지보수를 담당하였습니다.',
        skills: [
            'javascript',
            'nextjs9',
            'react',
            'ejs',
            'html',
        ],
        detail: [
            '메인페이지 리뉴얼',
            'sns 공유 기능 연동',
            '네이버 뉴스 스탠드 구현',
        ],
    },
    {
        project: '리모트 셀피',
        date: '2021.11 ~ 2021.12',
        description: '고정형 카메라를 통한 셀프 촬영 웹앱의 퍼블리싱 및 프론트엔드를 담당하였습니다.',
        skills: [
            'javascript',
            'react',
        ],
        detail: [
            'WebView를 활용한 화면 퍼블리싱',
            'Instagram Category Feed api 연동',
            'JavaScript Bridge를 이용한 카메라 기능 제어',
        ],
    },
    {
        project: 'K-Travelog',
        date: '2021.08 ~ 2021.10',
        description: '한국의 관광지를 소개해주는 웹사이트의 퍼블리싱을 담당하였습니다.',
        skills: [
            'javascript',
            'html',
            'css',
            'jquery',
        ],
        detail: [
            '전반적인 퍼블리싱 작업',
            'Flex 와 Grid를 이용한 레이아웃 구성',
            '웹 표준 및 접근성 최적화',
            '크로스 브라우징 처리',
        ],
    },
    {
        project: '실패 박람회',
        thumbnail: '/images/project/failexpo.png',
        date: '2021.07 ~ 2021.08',
        description: '실패 박람회라는 커뮤니티 형 웹사이트의 퍼블리싱을 담당하였습니다.',
        skills: [
            'javascript',
            'html',
            'css',
            'ejs',
            'jquery',
        ],
        detail: [
            '미디어 쿼리 반응형 웹 개발',
            '넘버 카운트 애니메이션 모듈 개발',
            '실패박람회 게시글에 대한 데이터 CRUD API 연동',
        ],
    },
    {
        project: 'HDC 영창',
        date: '2021.06 ~ 2021.07',
        description: 'HDC 영창 LMS 웹사이트의 퍼블리싱 업무를 일부 담당하였습니다. 강의 업로드 로직 퍼블리싱 및 기능과 비디오 플레이어를 주로 개발 하였습니다.',
        skills: [
            'javascript',
            'html',
            'css',
            'ejs',
            'jquery',
        ],
        detail: [
            '강의 업로드의 화면 퍼블리싱 및 업로드 api 연동',
            '비디오 플레이어 UI 구성 및 퍼블리싱',
        ],
    },
    {
        project: '국가인적자원 컨소시엄',
        date: '2021.03 ~ 2021.05',
        description: '한국산업인력공단에서 진행하는 컨소시엄 웹사이트의 퍼블리싱을 담당하였습니다. 공기업에서 진행하는 프로젝트로 웹 접근성과 웹 표준을 엄격히 준수하였습니다.',
        skills: [
            'javascript',
            'html',
            'css',
        ],
        detail: [
            'W3C 웹 표준 가이드라인 준수를 위한 HTML5 및 CSS3 사용',
            'ARIA 마크업 적용 및 키보드 네비게이션 최적화를 통한 웹 접근성 향상',
        ],
    },
    {
        project: 'KT-AI',
        date: '2021.02 ~ 2021.04',
        description: '음성 데이터를 텍스트로 변환하며 자막으로 생성하는 kt-ai 웹사이트의 퍼블리싱을 담당하였습니다.',
        skills: [
            'javascript',
            'html',
            'css',
            'ejs',
            'jquery',
        ],
        detail: [
            '화면의 전반적인 퍼블리싱 및 반응형 작업',
            'ajax를 통한 음성 인식 api 연동 및 리스트 퍼블리싱',
        ],
    },
];