name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/portfolio
  NAME: portfolio

jobs:
  deploy:
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.G_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ env.DOCKER_IMAGE }}:latest
  
      - name: Stop and Remove Previous Container
        run: |
          docker stop ${{ env.NAME }} || true
          docker rm ${{ env.NAME }} || true
  
      - name: Remove Unused Docker Images
        run: |
          docker image prune -f
          docker rmi $(docker images -f "dangling=true" -q) || true

      - name: Deploy Docker Container
        run: |
          docker run -d -p 80:3000 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:latest
